name: 'Run Checkov'
description: 'Run Checkov and report results to the job summary if there are failing checks'
inputs:
  path:
    description: 'Only run checks on files matching the specified path filter'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Check if merge commit
      id: check-merge-commit
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
      run: |
        merging=false
        [[ $EVENT == pull_request ]] && merging=true && fetch_depth=2
        echo "::set-output name=fetch-depth::${fetch_depth:-}"
        echo "::set-output name=merging::$merging"

    - name: Pull repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ steps.check-merge-commit.outputs.fetch-depth }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache-dependency-path: ./.github/workflows
        cache: 'pip'

    - name: Install Checkov
      run: echo "::group::pip output" && pip install checkov && echo "::endgroup::"
      shell: bash

    - name: Run Checkov on a pull request
      id: run-checkov-pr
      if: ${{ steps.check-merge-commit.outputs.merging == 'true' }}
      shell: bash
      env:
        DIR: ${{ inputs.path }}
        OUTPUT_FILE: ${{ runner.temp }}/checkov.output
      run: |
        files=$(git diff --name-only --diff-filter=d HEAD^...HEAD)
        [[ $DIR ]] && files=$(grep "$DIR" <<< "$files" || true)
        
        if [[ $files ]]; then
          mapfile -t files <<< "$files"
          read -ra files <<< "${files[@]/#/-f }"
          checkov --quiet --skip-framework secrets "${files[@]}" | tee "$OUTPUT_FILE"
        fi

    - name: Run Checkov on a directory
      id: run-checkov-dir
      if: ${{ steps.check-merge-commit.outputs.merging == 'false' && inputs.path != null }}
      shell: bash
      env:
        DIR: ${{ inputs.path }}
        OUTPUT_FILE: ${{ runner.temp }}/checkov.output
      run: checkov --quiet -d "$DIR" | tee "$OUTPUT_FILE"

    - name: Run Checkov on the repo
      id: run-checkov-repo
      if: ${{ steps.check-merge-commit.outputs.merging == 'false' && inputs.path == null }}
      shell: bash
      env:
        OUTPUT_FILE: ${{ runner.temp }}/checkov.output
      run: |
        checkov --quiet -d . | tee "$OUTPUT_FILE"
        [[ -d .github ]] && checkov --quiet -d .github | tee -a "$OUTPUT_FILE"

    - name: Report Checkov result
      if: ${{ failure() }}
      uses: alphagov/di-github-actions/report-step-result@5d1ae55ce54ef9c127090d0be477c58f3a3e32dd
      with:
        file-path: ${{ runner.temp }}/checkov.output
