name: 'Build an AWS SAM application'
description: 'Validates and builds the specified SAM application. The built artifact is found in the .aws-sam directory'
inputs:
  sam-template-file:
    description: 'Name of the SAM template file to use'
    required: false
  aws-role-arn:
    description: 'AWS role ARN to assume when validating the template'
    required: true
  aws-region:
    description: 'AWS region to use'
    required: false
    default: eu-west-2
  aws-session-name:
    description: 'Override the default AWS session name'
    required: false
  enable-beta-features:
    description: 'Use SAM beta features when building an application'
    required: false
    default: 'false'
  disable-cache:
    description: 'Set to true to use the --no-cached option'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Assume AWS Role
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: ${{ inputs.aws-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Validate SAM template
      shell: bash
      env:
        TEMPLATE_FILE: ${{ inputs.sam-template-file }}
      run: sam validate ${TEMPLATE_FILE:+--template-file $TEMPLATE_FILE}

    - name: Build SAM Application
      shell: bash
      env:
        TEMPLATE_FILE: ${{ inputs.sam-template-file }}
        BETA_FEATURES: ${{ inputs.enable-beta-features == 'true' }}
        DISABLE_CACHE: ${{ inputs.disable-cache == 'true' }}
      run: |
        sam build --parallel \
          $($DISABLE_CACHE || echo "--cached") \
          $($BETA_FEATURES && echo "--beta-features") \
          ${TEMPLATE_FILE:+--template-file $TEMPLATE_FILE}
