name: 'Delete stale apps'
description: 'Clean up apps that are older than the specified age'
inputs:
  age-threshold-days:
    description: 'The number of days to use as the threshold when checking when the app was last updated'
    required: false
    default: '30'
runs:
  using: 'composite'
  steps:
    - name: Clean up stale deployments
      run: ${{ github.action_path }}/delete-stale-apps.sh
      shell: bash
      env:
        THRESHOLD_DAYS: ${{ inputs.age-threshold-days }}
