name: 'Deploy to PaaS'
description: 'Deploy an application to PaaS using the Cloud Foundry client'
inputs:
  cf-org-name:
    description: 'The target organisation in PaaS'
    required: true
  cf-space-name:
    description: 'The target CF space in PaaS'
    required: true
  cf-username:
    description: 'The CF username of the PaaS account used to deploy the app'
    required: true
  cf-password:
    description: 'The PaaS account password'
    required: true
  app-name:
    description: 'The name of the deployed app. Overrides the name in the manifest and the one derived from branch name'
    required: false
  app-name-prefix:
    description: 'Derive the app name from the branch name and use the provided prefix'
    required: false
  variables:
    description: 'key=value pairs for variable substitution in the manifest, separated by newlines or "|"'
    required: false
  url:
    description: 'The PaaS deployment URL. Overrides the default <app-name>.london.cloudapps.digital URL'
    required: false
  rolling-deployment:
    description: 'Whether to use the rolling strategy when deploying'
    required: false
    default: 'false'
  instances:
    description: 'Number of app instances to deploy'
    required: false
    default: '1'
  start-command:
    description: "Command used to start the app"
    required: false
  manifest:
    description: "Path to the manifest file"
    required: false
  app-dir:
    description: "Path to the app directory"
    required: false
outputs:
  deployment-url:
    description: 'The PaaS deployment URL'
    value: ${{ steps.set-deployment-url.outputs.deployment-url }}
runs:
  using: composite
  steps:
    - name: Auth to PaaS
      uses: govuk-one-login/github-actions/paas/log-in-to-paas@92639740da7f67f445d10711e7b0fc1c9022f602
      with:
        cf-org-name: ${{ inputs.cf-org-name }}
        cf-space-name: ${{ inputs.cf-space-name }}
        cf-username: ${{ inputs.cf-username }}
        cf-password: ${{ inputs.cf-password }}

    - name: Parse variables
      id: parse-variables
      shell: bash
      env:
        PARAMETERS: ${{ inputs.variables }}
        ASSOCIATIVE_ARRAY: 'true'
        PARSE: ${{ github.action_path }}/../../scripts/parse-parameters.sh
      run: echo "variables=$($PARSE)" >> "$GITHUB_OUTPUT"

    - name: Create variables file
      shell: bash
      env:
        VARS_FILE: ${{ runner.temp }}/variables.yaml
        VARS: ${{ steps.parse-variables.outputs.variables }}
      run: |
        declare -A variables
        eval "variables=(${VARS})"        
        for variable in "${!variables[@]}"; do
          echo "$variable: ${variables[$variable]}" >> "$VARS_FILE"
        done

    - name: Set deployment hostname
      id: set-deployment-hostname
      if: ${{ inputs.app-name == null && inputs.app-name-prefix != null }}
      shell: bash
      env:
        DOWNCASE: true
        LENGTH_LIMIT: 63
        REPLACE_UNDERSCORES: true
        PREFIX: ${{ inputs.app-name-prefix }}
        TRANSFORM: ${{ github.action_path }}/../../scripts/transform-branch-name.sh
      run: |
        app_name=$($TRANSFORM)
        echo "app-name=$app_name" >> "$GITHUB_OUTPUT"
        echo "App name: \`$app_name\`" | tee "$GITHUB_STEP_SUMMARY"

    - name: Set app name
      shell: bash
      env:
        APP_NAME: ${{ steps.set-deployment-hostname.outputs.app-name || inputs.app-name }}
      run: echo "APP_NAME=$APP_NAME" >> "$GITHUB_ENV"

    - name: Set deployment URL
      if: ${{ inputs.url != null || env.APP_NAME != null }}
      id: set-deployment-url
      shell: bash
      env:
        URL: ${{ inputs.url }}
        HOSTNAME: ${{ env.APP_NAME }}
      run: echo "deployment-url=${URL:-https://${HOSTNAME}.london.cloudapps.digital}" >> "$GITHUB_OUTPUT"

    - name: Push to PaaS
      shell: bash
      env:
        ROLLING_DEPLOYMENT: ${{ inputs.rolling-deployment == 'true' }}
        VARS_FILE: ${{ runner.temp }}/variables.yaml
        INSTANCES: ${{ inputs.instances }}
        APP_DIR: ${{ inputs.app-dir }}
        START_COMMAND: ${{ inputs.start-command }}
        MANIFEST_PATH: ${{ inputs.manifest }}
      run: |
        $ROLLING_DEPLOYMENT && strategy="rolling"        

        cf push "${APP_NAME:-}" \
          ${APP_DIR:+--path "$APP_DIR"} \
          ${MANIFEST_PATH:+--manifest "$MANIFEST_PATH"} \
          ${START_COMMAND:+--start-command "$START_COMMAND"} \
          --strategy ${strategy:-""} \
          --instances "$INSTANCES" \
          --vars-file "$VARS_FILE"
