name: 'Delete SAM stacks'
description: 'Delete existing AWS SAM stacks and optionally check their state'
inputs:
  stack-names:
    description: 'Names of the stacks to delete (space or newline-delimited string)'
    required: true
  aws-region:
    description: 'AWS region to use'
    required: false
    default: eu-west-2
  only-if-failed:
    description: 'Delete a stack only if it is in one of the failed states'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Check stacks exist
      id: check-stacks-exist
      if: ${{ inputs.stack-names }}
      shell: bash
      env:
        STACK_NAMES: ${{ inputs.stack-names }}
        CHECK_STACKS: ${{ github.action_path }}/../../scripts/aws/ecr/check-stacks-exist.sh
      run: |
        declare -A stacks && eval "stacks=($($CHECK_STACKS))"
        echo "existing-stacks=${stacks[existing-stacks]:-}" >> "$GITHUB_OUTPUT"

    - name: Delete stacks
      id: delete-stacks
      if: ${{ steps.check-stacks-exist.outputs.existing-stacks != null }}
      run: ${{ github.action_path }}/delete-stacks.sh
      shell: bash
      env:
        STACK_NAMES: ${{ steps.check-stacks-exist.outputs.existing-stacks }}
        ONLY_FAILED: ${{ inputs.only-if-failed == 'true' }}
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Report results
      if: ${{ always() && join(steps.delete-stacks.outputs.*, '') != null }}
      shell: bash
      env:
        DELETED_STACKS: ${{ steps.delete-stacks.outputs.deleted-stacks }}
        FAILED_STACKS: ${{ steps.delete-stacks.outputs.failed-stacks }}
        REPORT: ${{ github.action_path }}/../../scripts/report-step-result/print-list.sh
      run: |
        [[ -z $DELETED_STACKS ]] ||
          VALUES=$DELETED_STACKS MESSAGE="Deleted stacks" SINGLE_MESSAGE="Deleted stack %s" $REPORT |
          tee "$GITHUB_STEP_SUMMARY"
        
        [[ -z $FAILED_STACKS ]] ||
          VALUES=$FAILED_STACKS MESSAGE="Failed to delete stacks" SINGLE_MESSAGE="Failed to delete stack %s" $REPORT |
          tee "$GITHUB_STEP_SUMMARY"
