name: 'Delete SAM stacks'
description: 'Delete existing AWS SAM stacks and optionally check their state'
inputs:
  stack-names:
    description: 'Names of the stacks to delete (space or newline-delimited string)'
    required: true
  aws-region:
    description: 'AWS region to use'
    required: false
    default: eu-west-2
  only-if-failed:
    description: 'Delete a stack only if it is in one of the failed states'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Check stacks exist
      id: check-stacks-exist
      if: ${{ inputs.stack-names }}
      uses: alphagov/di-github-actions/sam/check-stacks-exist@4460b10baa63ab00496fe5f5f39495d428018a27
      with:
        stack-names: ${{ inputs.stack-names }}
        verbose: true

    - name: Delete stacks
      if: ${{ steps.check-stacks-exist.outputs.existing-stacks }}
      run: ${{ github.action_path }}/delete-stacks.sh
      shell: bash
      env:
        STACK_NAMES: ${{ steps.check-stacks-exist.outputs.existing-stacks }}
        ONLY_FAILED: ${{ inputs.only-if-failed == 'true' }}
        AWS_REGION: ${{ inputs.aws-region }}
