name: 'Delete SAM stacks'
description: 'Delete existing AWS SAM stacks and optionally check their state'
inputs:
  stack-names:
    description: 'Names of the stacks to delete (space or newline-delimited string)'
    required: true
  aws-region:
    description: 'AWS region to use'
    required: false
    default: eu-west-2
  only-if-failed:
    description: 'Delete a stack only if it is in one of the failed states'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Check stacks exist
      id: check-stacks-exist
      if: ${{ inputs.stack-names }}
      uses: alphagov/di-github-actions/sam/check-stacks-exist@b78d425fd7bf96b590f946bdf6dc37e720a1325b
      with:
        stack-names: ${{ inputs.stack-names }}
        verbose: true

    - name: Delete stacks
      id: delete-stacks
      if: ${{ steps.check-stacks-exist.outputs.existing-stacks }}
      run: ${{ github.action_path }}/delete-stacks.sh
      shell: bash
      env:
        STACK_NAMES: ${{ steps.check-stacks-exist.outputs.existing-stacks }}
        ONLY_FAILED: ${{ inputs.only-if-failed == 'true' }}
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Report deleted stacks
      if: ${{ always() && steps.delete-stacks.outputs.deleted-stacks != null }}
      shell: bash
      env:
        VALUES: ${{ steps.delete-stacks.outputs.deleted-stacks }}
        MESSAGE: Deleted stacks
        SINGLE_MESSAGE: Deleted stack %s
        REPORT: ${{ runner.temp }}/deleted-stacks-report
        SCRIPT: ${{ github.action_path }}/../../scripts/report-step-result/print-list.sh
      run: $SCRIPT >> "$REPORT"

    - name: Report failed stacks
      if: ${{ failure() && steps.delete-stacks.outputs.failed-stacks != null }}
      shell: bash
      env:
        VALUES: ${{ steps.delete-stacks.outputs.failed-stacks }}
        MESSAGE: Failed to delete stacks
        SINGLE_MESSAGE: Failed to delete stack %s
        REPORT: ${{ runner.temp }}/deleted-stacks-report
        SCRIPT: ${{ github.action_path }}/../../scripts/report-step-result/print-list.sh
      run: $SCRIPT >> "$REPORT"

    - name: Report results
      if: ${{ always() }}
      shell: bash
      env:
        REPORT: ${{ runner.temp }}/deleted-stacks-report
      run: |
        ! [[ -f $REPORT ]] || tee "$GITHUB_STEP_SUMMARY" < "$REPORT"
