name: "Delete SAM stacks"
description: "Delete existing AWS SAM stacks and optionally check their state"
inputs:
  aws-role-arn:
    description: "AWS role ARN to assume when validating the template"
    required: false
  aws-region:
    description: "AWS region to use"
    required: false
    default: eu-west-2
  aws-session-name:
    description: "Override the default AWS session name"
    required: false
  stack-names:
    description: "Names of the stacks to delete (space or newline-delimited string)"
    required: true
  only-if-failed:
    description: "Delete a stack only if it is in one of the failed states"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Assume AWS Role
      if: ${{ inputs.aws-role-arn != null }}
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: ${{ inputs.aws-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Delete stacks
      if: ${{ inputs.stack-names != null }}
      run: ${{ github.action_path }}/../../scripts/aws/sam/delete-stacks.sh
      shell: bash
      env:
        STACK_NAMES: ${{ inputs.stack-names }}
        ONLY_FAILED: ${{ inputs.only-if-failed == 'true' }}
