name: "Upload SAM package to secure pipelines"
description: "Upload a SAM application package to an S3 bucket for deployment with secure pipelines"
inputs:
  aws-role-arn:
    description: "ARN of AWS role to assume when uploading the package to S3"
    required: false
  aws-region:
    description: "AWS region to use"
    required: false
    default: eu-west-2
  artifact-bucket-name:
    description: "The name of the bucket to upload the SAM artifact to"
    required: true
  signing-profile-name:
    description: "The name of the profile to use for code signing"
    required: true
  artifact-name:
    description: "Name of the artifact containing the built SAM application"
    required: false
  template:
    description: "Filepath of the SAM application template"
    required: false
    default: template.yaml
  pull-repository:
    description: "Pull the repository before uploading the package"
    required: false
    default: "true"
  working-directory:
    description: "The working directory containing the SAM app"
    required: false
  pipeline-name:
    description: "The name of the deployment pipeline"
    required: false
outputs:
  pipeline-url:
    description: "The URL of the pipeline consuming the uploaded artifact"
    value: ${{ steps.get-pipeline-url.outputs.pipeline-url }}
runs:
  using: composite
  steps:
    - name: Pull repository
      if: ${{ inputs.pull-repository == 'true' }}
      uses: actions/checkout@v3

    - name: Get distribution artifact
      if: ${{ inputs.artifact-name != null }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}

    - name: Assume AWS Role
      if: ${{ inputs.aws-role-arn != null }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Validate SAM template
      shell: bash
      env:
        TEMPLATE: ${{ inputs.template }}
        AWS_REGION: ${{ inputs.aws-region }}
        VALIDATE: ${{ github.action_path }}/../../scripts/aws/sam/validate-template.sh
      run: $VALIDATE

    - name: Upload package
      uses: alphagov/di-devplatform-upload-action@v3.3
      with:
        signing-profile-name: ${{ inputs.signing-profile-name }}
        artifact-bucket-name: ${{ inputs.artifact-bucket-name }}
        working-directory: ${{ inputs.working-directory }}
        template-file: ${{ inputs.template }}

    - name: Get pipeline URL
      id: get-pipeline-url
      if: ${{ inputs.pipeline-name != null }}
      shell: bash
      env:
        REGION: ${{ inputs.aws-region }}
        PIPELINE_NAME: ${{ inputs.pipeline-name }}
      run: |
        url="https://${REGION}.console.aws.amazon.com/codesuite/codepipeline/pipelines/${PIPELINE_NAME}/view"
        echo "pipeline-url=$url" >> "$GITHUB_OUTPUT"
