name: 'Parse parameters'
description: 'Parse parameters encoded as key-value pairs delimited by "|" or newlines into a key=value pairs string'
inputs:
  parameters:
    description: 'The parameters to parse'
    required: true
  env-var-name:
    description: 'Name of an env var to store a string representation of an associative array containing the parsed params'
    required: false
  associative-array:
    description: "Encode output as a string representing an associative array ([key1]=value1 ... [keyN]=valueN)"
    required: false
    default: 'false'
outputs:
  parsed-parameters:
    description: 'A string representation of a regular or an associative array containing the parsed params'
    value: ${{ steps.parse-parameters.outputs.parsed-parameters }}
runs:
  using: composite
  steps:
    - name: Parse parameters
      id: parse-parameters
      run: ${{ github.action_path }}/parse-params.sh
      shell: bash
      env:
        PARAMS: ${{ inputs.parameters }}
        ENV_VAR_NAME: ${{ inputs.env-var-name }}
        ASSOCIATIVE_ARRAY: ${{ inputs.associative-array == 'true' }}
