name: "Build Docker image"
description: "Build and push a Docker image to an ECR repo"
inputs:
  aws-role-arn:
    description: "ARN of AWS role to assume when authenticating to ECR"
    required: false
  aws-region:
    description: "AWS region to use"
    required: false
    default: eu-west-2
  aws-session-name:
    description: "Override the default AWS session name"
    required: false
  registry:
    description: "Registry which contains the specified repository"
    required: false
  repository:
    description: "ECR repository name"
    required: true
  image-version:
    description: "A unique version identifier to be used as an image tag"
    required: false
    default: latest
  image-tags:
    description: "A list list additional tags to apply to the image, delimited by spaces or newlines"
    required: false
  immutable-tags:
    description: "Whether the repository is immutable (tags cannot be overwritten)"
    required: false
    default: "true"
  dockerfile-path:
    description: "Path to the Dockerfile to use"
    required: false
  build-path:
    description: "Path to the directory to build"
    required: false
    default: "."
outputs:
  registry:
    description: "Registry to which the Docker image was pushed"
    value: ${{ inputs.registry || steps.login-ecr.outputs.registry }}
  repository:
    description: "Pass through the repository used to push the Docker image"
    value: ${{ inputs.repository }}
  image-version:
    description: "Pass through the version of the Docker image pushed to ECR"
    value: ${{ inputs.image-version }}
  image-digest:
    description: "Digest of the Docker image pushed to ECR"
    value: ${{ steps.check-image-exists.outputs.image-digest || steps.report-pushed-image.outputs.image-digest }}
  image-tags:
    description: "Pass through the additional tags applied to the Docker image"
    value: ${{ inputs.image-tags }}
  image-uri:
    description: "Image URI in the format <registry>/<repository>@<digest>"
    value: ${{ steps.set-image-uri.outputs.image-uri }}
runs:
  using: composite
  steps:
    - name: Assume AWS Role
      if: ${{ inputs.aws-role-arn != null }}
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: ${{ inputs.aws-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to ECR
      if: ${{ inputs.registry == null }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check image exists
      id: check-image-exists
      if: ${{ inputs.immutable-tags == 'true' && inputs.image-version != null }}
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAGS: ${{ inputs.image-version }}
        CHECK_IMAGE: ${{ github.action_path }}/../../../scripts/aws/ecr/check-image-exists.sh
      run: |
        image_digest=$($CHECK_IMAGE)
        echo "image-digest=$image_digest" >> "$GITHUB_OUTPUT"

    - name: Delete previous image version
      if: ${{ inputs.immutable-tags == 'true' && steps.check-image-exists.outputs.image-digest == null }}
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAGS: ${{ inputs.image-tags }}
        CHECK_IMAGE: ${{ github.action_path }}/../../../scripts/aws/ecr/check-image-exists.sh
        REPORT: ${{ github.action_path }}/../../../scripts/report-step-result/print-file.sh
        TITLE: Deleted previous image version
        LANGUAGE: shell
      run: |
        image_digest=$($CHECK_IMAGE)
        if ! [[ $image_digest ]]; then
          echo "Previous version of image with tags '$IMAGE_TAGS' not found"
          exit
        fi
        
        echo "Deleting previous image version..."
        aws ecr batch-delete-image \
          --repository-name "$REPOSITORY" \
          --image-ids imageDigest="$image_digest" \
          --output text | $REPORT | tee "$GITHUB_STEP_SUMMARY" 

    - name: Build Docker image
      id: build-image
      if: ${{ steps.check-image-exists.outputs.image-digest == null }}
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry || steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_VERSION: ${{ inputs.image-version }}
        IMAGE_TAGS: ${{ inputs.image-tags }}
        DOCKERFILE: ${{ inputs.dockerfile-path }}
        BUILD_PATH: ${{ inputs.build-path }}
      run: |
        echo "::group::Build image"
        read -ra tags <<< "$IMAGE_TAGS"
        read -ra tags <<< "${tags[@]/#/--tag $REGISTRY/$REPOSITORY:}"        
        image_name=${IMAGE_VERSION:+$REGISTRY/$REPOSITORY:$IMAGE_VERSION}        
        docker build ${image_name:+--tag $image_name} "${tags[@]}" ${DOCKERFILE:+--file $DOCKERFILE} "$BUILD_PATH"
        echo "::endgroup::"

    - name: Push Docker image
      id: push-docker-image
      if: ${{ steps.build-image.outcome == 'success' }}
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry || steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
      run: |
        echo "::group::Push image"
        docker push --all-tags "$REGISTRY/$REPOSITORY"
        echo "::endgroup::"

    - name: Report pushed image
      id: report-pushed-image
      if: ${{ steps.push-docker-image.outcome == 'success' }}
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry || steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
      run: |
        mapfile -t tags < <(docker image ls "$REGISTRY/$REPOSITORY" --format '{{.Tag}}')
        mapfile -t digests < <(docker image ls "$REGISTRY/$REPOSITORY" --format '{{.Digest}}' | sort -u)
        
        if [[ ${#digests[@]} -ne 1 ]]; then
          echo "Expected one image digest for image \`$REGISTRY/$REPOSITORY\` but got \`${digests[*]}\`"
          exit 1
        fi
        
        digest=${digests[*]}
        [[ ${#tags[@]} -le 1 ]] || plural=true
        [[ ${#tags[@]} -le 0 ]] || tag_msg="tag${plural:+s} \`${tags[*]}\`"
        
        echo "Pushed image with ${tag_msg:-digest \`$digest\`} to repository \`$REPOSITORY\`" >> "$GITHUB_STEP_SUMMARY"
        echo "image-digest=$digest" >> "$GITHUB_OUTPUT"

    - name: Set image URI
      id: set-image-uri
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry || steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_DIGEST: ${{ steps.check-image-exists.outputs.image-digest || steps.report-pushed-image.outputs.image-digest }}
      run: echo "image-uri=${REGISTRY}/${REPOSITORY}:@${IMAGE_DIGEST}" >> "$GITHUB_OUTPUT"
