name: 'Beautify branch name'
description: 'Modify the branch name to be usable in deployment and host names'
inputs:
  branch-name:
    description: "Override the branch name to transform"
    required: false
  downcase:
    description: 'Whether to downcase all letters in the branch name'
    required: false
    default: 'true'
  underscores-to-hyphens:
    description: 'Whether to replace all underscores with hyphens'
    required: false
    default: 'true'
  tidy-dependabot-branch:
    description: 'Whether to beautify dependabot generated branch names to db-function-package-version'
    required: false
    default: 'false'
  length-limit:
    description: 'Maximum length of the modified string'
    required: false
    default: '200'
  prefix:
    description: "'prefix-' will be prepended to the returned string. Included in the length limit"
    required: false
  set-env-var:
    description: "Name of the environment variable to set in the job with the value of the modified branch name"
    required: false
  usage:
    description: 'The purpose for which the transformed name is used - for logging purposes only'
    required: false
outputs:
  pretty-branch-name:
    description: 'Beautified branch name'
    value: ${{ steps.transform-branch-name.outputs.pretty-branch-name }}
runs:
  using: 'composite'
  steps:
    - name: Transform branch name
      id: transform-branch-name
      run: ${{ github.action_path }}/transform-branch-name.sh
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.branch-name }}
        DOWNCASE_NAME: ${{ inputs.downcase == 'true' }}
        UNDERSCORES_TO_HYPHENS: ${{ inputs.underscores-to-hyphens == 'true' }}
        TIDY_DEPENDENCY_BOT_BRANCH: ${{ inputs.tidy-dependabot-branch == 'true' }}
        TOTAL_LENGTH_LIMIT: ${{ inputs.length-limit }}
        PREFIX: ${{ inputs.prefix }}
        SET_ENV_VAR: ${{ inputs.set-env-var }}
        USAGE: ${{ inputs.usage }}
