name: 'Check linting'
description: 'Run Prettier and/or ESLint and report results to the job summary if there are failing checks'
inputs:
  run-prettier:
    description: 'Whether to run Prettier'
    required: false
    default: 'true'
  run-eslint:
    description: 'Whether to run ESLint'
    required: false
    default: 'true'
  error-on-warnings:
    description: 'Treat warnings as errors'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Check if merge commit
      id: check-merge-commit
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
      run: |
        merging=false
        [[ $EVENT == pull_request ]] && merging=true && fetch_depth=2
        echo "fetch-depth=${fetch_depth:-}" >> "$GITHUB_OUTPUT"
        echo "merging=$merging" >> "$GITHUB_OUTPUT"

    - name: Pull repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ steps.check-merge-commit.outputs.fetch-depth }}

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install linting tools
      shell: bash
      run: |
        echo "::group::Install packages"
        npm install prettier eslint
        echo "::endgroup::"

    - name: Get files to check
      id: get-files
      if: ${{ steps.check-merge-commit.outputs.merging == 'true' }}
      shell: bash
      run: |
        mapfile -t files < <(git diff --name-only --diff-filter=d HEAD^...HEAD)
        echo "files=${files[*]}" >> "$GITHUB_OUTPUT"

    - name: Run Prettier
      id: run-prettier
      if: ${{ inputs.run-prettier == 'true' }}
      shell: bash
      env:
        FILES: ${{ steps.get-files.outputs.files }}
        OUTPUT_FILE: ${{ runner.temp }}/prettier.output
      run: |
        echo "::notice::Running Prettier..."
        read -ra files <<< "$FILES"
        [[ ${#files[@]} -eq 0 ]] && files=(.)
        npx prettier --check "${files[@]}" 2>&1 | tee "$OUTPUT_FILE"        

    - name: Run ESLint
      id: run-eslint
      if: ${{ (success() || failure() && steps.run-prettier.outcome == 'failure') && inputs.run-eslint == 'true' }}
      shell: bash
      env:
        TYPES: .jsx .js .ts
        FILES: ${{ steps.get-files.outputs.files }}
        STRICT: ${{ inputs.error-on-warnings == 'true' }}
        OUTPUT_FILE: ${{ runner.temp }}/eslint.output
      run: |
        echo "::notice::Running ESLint..."
        
        if $STRICT; then
          max_warnings="--max-warnings=0"
        fi
        
        if [[ -n $FILES ]]; then
          files="$(tr ' ' '\n' <<< "$FILES")"
          read -ra types <<< "$(tr '\n' ' ' <<< "$TYPES")"
          filetype_regex="$(IFS="|"; echo ".*\.(${types[*]##.})$")"
        
          if es_files="$(grep -E --regexp="$filetype_regex" <<< "$files")"; then
            mapfile -t es_files <<< "$es_files"
          else
            echo "No files to check"
            exit 0
          fi
        else
          es_files=(.)
        fi
        
        npx eslint ${max_warnings:-} "${es_files[@]}" | tee "$OUTPUT_FILE"  

    - name: Write Prettier results
      id: report-prettier
      if: ${{ failure() && steps.run-prettier.outcome == 'failure' }}
      uses: alphagov/di-github-actions/report-step-result/print-file@5b880e99b78950f38202922aa51e3ccfae9bc13a
      with:
        file-path: ${{ runner.temp }}/prettier.output
        output-file-path: ${{ runner.temp }}/checks.report
        code-block: true
        title: Prettier

    - name: Write ESLint results
      id: report-eslint
      if: ${{ failure() && steps.run-eslint.outcome == 'failure' }}
      uses: alphagov/di-github-actions/report-step-result/print-file@5b880e99b78950f38202922aa51e3ccfae9bc13a
      with:
        file-path: ${{ runner.temp }}/eslint.output
        output-file-path: ${{ runner.temp }}/checks.report
        code-block: true
        title: ESLint

    - name: Report results
      if: ${{ (failure() && steps.report-prettier.outcome == 'success') || steps.report-eslint.outcome == 'success' }}
      uses: alphagov/di-github-actions/report-step-result/print-file@5b880e99b78950f38202922aa51e3ccfae9bc13a
      with:
        file-path: ${{ runner.temp }}/checks.report
