name: "Check image exists"
description: "Check if the image with the specified tags exists in the queried ECR repo"
inputs:
  repository:
    description: "ECR repository name"
    required: true
  image-tags:
    description: "Tags associated with the targeted image, delimited by spaces or newlines"
    required: true
outputs:
  image-exists:
    description: "Boolean indicating whether the image exists"
    value: ${{ steps.check-image-exists.outputs.image-exists }}
  image-digest:
    description: "Digest of the image if it exists"
    value: ${{ steps.check-image-exists.outputs.image-digest }}
runs:
  using: composite
  steps:
    - name: Check image exists
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAGS: ${{ inputs.image-tags }}
        CHECK_IMAGE: ${{ github.action_path }}/../../../scripts/aws/ecr/check-image-exists.sh
      run: |
        image_digest=$($CHECK_IMAGE)
        [[ $image_digest ]] && image_exists=true || image_exists=false
        echo "image-exists=$image_exists" >> "$GITHUB_OUTPUT"
        echo "image-digest=$image_digest" >> "$GITHUB_OUTPUT"
