name: 'Get image digests'
description: 'Get the digests of images in an ECR repository with the specified tags, if they exist in the repo'
inputs:
  repository:
    description: 'ECR repository name'
    required: true
  image-tags:
    description: 'Tags associated with the targeted images, delimited by spaces or newlines'
    required: true
outputs:
  image-digests:
    description: 'A string representation of an array containing the digests of the images with the specified tags'
    value: ${{ steps.get-image-digests.outputs.image-digests }}
runs:
  using: composite
  steps:
    - name: Get image digests
      id: get-image-digests
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAGS: ${{ inputs.image-tags }}
        IMAGE_DIGESTS: ${{ github.action_path }}/../../../scripts/aws/ecr/get-image-digests.sh
      run: |
        image_digests=$($IMAGE_DIGESTS)
        echo "image-digests=$image_digests" >> "$GITHUB_OUTPUT"
