name: Beautify branch name test

on: pull_request

jobs:
  run-tests:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v3


      - name: Downcase branch name
        id: downcase
        uses: ./beautify-branch-name
        with:
          branch-name: BRANCH-NAME-with-UPPer-CASe-letterS
          downcase: true

      - name: Check branch name downcased
        run: |
          [[ ${{ steps.downcase.outputs.pretty-branch-name }} == branch-name-with-upper-case-letters ]]


      - name: Replace underscores
        id: replace-underscores
        uses: ./beautify-branch-name
        with:
          branch-name: branch_name_with-underscores
          underscores-to-hyphens: true

      - name: Check underscores replaced
        run: |
          [[ ${{ steps.replace-underscores.outputs.pretty-branch-name }} == branch-name-with-underscores ]]


      - name: Truncate length
        id: truncate-length
        uses: ./beautify-branch-name
        with:
          branch-name: very-long-branch-name
          length-limit: 12

      - name: Check branch name truncated
        run: |
          [[ ${{ steps.truncate-length.outputs.pretty-branch-name }} == very-long-br ]]


      - name: Prepend prefix
        id: prepend-prefix
        uses: ./beautify-branch-name
        with:
          branch-name: long-branch-name
          prefix: prefix
          length-limit: 20

      - name: Check prefix prepended
        run: |
          [[ ${{ steps.prepend-prefix.outputs.pretty-branch-name }} == prefix-long-branch-n ]]


      - name: Validate length limit
        id: validate-length-limit
        continue-on-error: true
        uses: ./beautify-branch-name
        with:
          branch-name: very-long-branch-name
          length-limit: -1

      - name: Check length limit not validated
        if: ${{ steps.validate-length-limit.outcome != 'failure' }}
        run: |
          echo "Invalid length limit has not been rejected"
          exit 1
      

      - name: Set environment variable
        uses: ./beautify-branch-name
        with:
          branch-name: branch-name
          set-env-var: PRETTY_BRANCH_NAME

      - name: Check environment variable set
        run: |
          [[ $PRETTY_BRANCH_NAME == branch-name ]]
