name: Print list to step summary test

on: pull_request
permissions: read-all

jobs:
  run-tests:
    name: Test action
    runs-on: ubuntu-latest
    env:
      STUB_REPORT_FILE_NAME: test-result.txt
    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Write stub report
        env:
          REPORT_FILE: ${{ runner.temp }}/${{ env.STUB_REPORT_FILE_NAME }}
        run: echo "Stub report" >> "$REPORT_FILE"


      - name: Report single value
        uses: ./report-step-result/print-list
        with:
          values: one
          message: Reported values
          output-file-path: ${{ runner.temp }}/report.txt
          code-block: false

      - name: Check single value reported
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values: one
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Accumulate results
        uses: ./report-step-result/print-list
        with:
          values: two
          message: Reported other values
          output-file-path: ${{ runner.temp }}/report.txt
          code-block: false

      - name: Check result accumulated
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values: one
          Reported other values: two
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Use single value message
        uses: ./report-step-result/print-list
        with:
          values: one-and-only
          message: Reported values
          single-message: Reported single value
          output-file-path: ${{ runner.temp }}/report-single-value.txt
          code-block: false

      - name: Check single value message used
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-single-value.txt
        run: |
          cat << 'EOF' > expected_file
          Reported single value: one-and-only
          EOF
          
          diff "$OUTPUT_FILE" expected_file


      - name: Replace token in single value message
        uses: ./report-step-result/print-list
        with:
          values: one-and-only
          message: Reported values
          single-message: Reported %s value
          output-file-path: ${{ runner.temp }}/report-single-value-token.txt
          code-block: false

      - name: Check token replaced in single value message
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-single-value-token.txt
        run: |
          cat << 'EOF' > expected_file
          Reported one-and-only value
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Use code block for single value
        uses: ./report-step-result/print-list
        with:
          values: single
          message: Reported values
          output-file-path: ${{ runner.temp }}/report-code-block-single.txt
          code-block: true

      - name: Check code block used for single value
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-code-block-single.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values: `single`
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Print multiple values with extra spaces
        uses: ./report-step-result/print-list
        with:
          values: "   one two three     four   five    "
          message: Reported values
          output-file-path: ${{ runner.temp }}/report-multiple-values.txt
          code-block: false

      - name: Check multiple values with extra spaces reported
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-multiple-values.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values:
            - one
            - two
            - three
            - four
            - five
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Use code block for multiple values
        uses: ./report-step-result/print-list
        with:
          values: one two three
          message: Reported values
          output-file-path: ${{ runner.temp }}/report-code-block-multiple.txt
          code-block: true

      - name: Check code block used for multiple values
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-code-block-multiple.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values:
            - `one`
            - `two`
            - `three`
          EOF

          [[ $(cat "$OUTPUT_FILE") == $(cat expected_file) ]]


      - name: Print multi-line values
        uses: ./report-step-result/print-list
        with:
          output-file-path: ${{ runner.temp }}/report-multiline-values.txt
          code-block: false
          message: Reported values
          values: |
            one
            two
            three

      - name: Check multi-line values reported
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-multiline-values.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values:
            - one
            - two
            - three
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Print multi-line values with spaces and empty lines
        uses: ./report-step-result/print-list
        with:
          output-file-path: ${{ runner.temp }}/report-multiline-values-spaces.txt
          code-block: false
          message: Reported values
          values: |
            
            
            one two   three
            blue pink yellow
            
            
            apple banana orange
            
            seafood pasta sushi



      - name: Check multi-line values with spaces and empty lines reported
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-multiline-values-spaces.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values:
            - one two   three
            - blue pink yellow
            - apple banana orange
            - seafood pasta sushi
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Use code block for multi-line values with spaces
        uses: ./report-step-result/print-list
        with:
          output-file-path: ${{ runner.temp }}/report-multiline-values-block.txt
          code-block: true
          message: Reported values
          values: |
            one two three
            blue pink yellow
            apple banana orange


      - name: Check code block used for multi-line values with spaces
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-multiline-values-block.txt
        run: |
          cat << 'EOF' > expected_file
          Reported values:
            - `one two three`
            - `blue pink yellow`
            - `apple banana orange`
          EOF

          diff "$OUTPUT_FILE" expected_file


      - name: Complete without an error when given an empty list
        id: terminate-successfully
        uses: ./report-step-result/print-list
        with:
          output-file-path: ${{ runner.temp }}/report-empty-list.txt
          code-block: false
          message: Reported values
          values: "     "

      - name: Check action completed without an error given an empty list
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-empty-list.txt
        run: |
          [[ -s $OUTPUT_FILE ]] && echo "Expected the output file to be empty" && exit 1 || exit 0


      - name: Complete without an error when given an empty multi-line value
        id: terminate-successfully-multiline
        uses: ./report-step-result/print-list
        with:
          output-file-path: ${{ runner.temp }}/report-empty-list-multiline.txt
          code-block: false
          message: Reported values
          quiet: false
          values: |








      - name: Check action completed without an error given an empty multi-line value
        env:
          OUTPUT_FILE: ${{ runner.temp }}/report-empty-list-multiline.txt
        run: |
          [[ -s $OUTPUT_FILE ]] && echo "Expected the output file to be empty" && exit 1 || exit 0
